"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup
from setuptools import setup, find_packages
import tcp_tunnel


setup(name="tcp-tunnel",
      version=tcp_tunnel.VERSION,
      packages=find_packages(include=['tcp_tunnel', 'tcp_tunnel.*',]),
      author='Mason Sun',
      author_email='sqxccdy@icloud.com',
      long_description=open("README.md", "r").read(),
      long_description_content_type="text/markdown",
      include_package_data=True,
      exclude_package_date={'': ['.gitignore']},
      keywords='tcp, tunnel, tcp-tunnel, tcptunnel',
      license='MIT License',
      url='https://github.com/sqxccdy/tcp-tunnel.git',
      entry_points={
          'console_scripts': [
              'aiomq_server=aiomq.server:run'
          ]
      },
      install_requires=[],
      classifiers=[
          'Development Status :: 1 - Planning',
          'Intended Audience :: Developers',
          'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)',
          'Operating System :: OS Independent',
          'Natural Language :: Chinese (Simplified)',
          'Programming Language :: Python',
          'Programming Language :: Python :: 3.8',
          'Programming Language :: Python :: 3.7',
          'Programming Language :: Python :: 3.6',
          'Topic :: Software Development :: Libraries',
          'Topic :: Utilities',
      ],
      )
